<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Minimum Withdraw  USDT 1_slider-stop-whole</name>
   <tag></tag>
   <elementGuidId>27ce761d-6a26-4431-a367-9989e9ecde24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.slider-stop-whole</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[3]/div/div/div[2]/div[2]/div[4]/div[2]/button[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d2f4e327-1827-4b73-9cdb-9550bef6871c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slider-stop-whole</value>
      <webElementGuid>feabc382-80c1-4718-bbf5-4c4a01f47f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;vx-app&quot;]/div[@class=&quot;app-content&quot;]/div[@class=&quot;withdraw&quot;]/div[@class=&quot;withdraw__wrapper&quot;]/div[@class=&quot;withdraw__idr&quot;]/div[@class=&quot;withdraw__idr__main&quot;]/div[@class=&quot;slider-container&quot;]/div[2]/button[@class=&quot;slider-stop-whole&quot;]</value>
      <webElementGuid>beeb1226-a2df-42f0-bd03-77cfbc283051</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div/div[2]/div[2]/div[4]/div[2]/button[5]</value>
      <webElementGuid>945a66d0-25f4-4b56-8220-0c8e5e8b8bee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[5]</value>
      <webElementGuid>65f72b44-02ef-43e4-9852-699a37d96067</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
