<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Select Coin</name>
   <tag></tag>
   <elementGuidId>cc427e3d-875b-4e87-b1ac-d59ffdd8739d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[2]/div/div/div/div/div/div/div/p[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.main-buysell__header__coin__dropdown</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>a8bd0889-d48a-47a0-8f51-ea3f53aa12d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main-buysell__header__coin__dropdown</value>
      <webElementGuid>5700c3ea-3193-4787-bf53-a68d79944e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Coin</value>
      <webElementGuid>479f41f8-e9bb-4166-b652-20c13d853f9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;app-content&quot;]/div[@class=&quot;buysell&quot;]/div[@class=&quot;buysell__wrapper&quot;]/div[@class=&quot;buysell__main&quot;]/div[@class=&quot;main-buysell&quot;]/div[@class=&quot;main-buysell__wrapper&quot;]/div[@class=&quot;main-buysell__header&quot;]/div[@class=&quot;main-buysell__header__coin&quot;]/p[@class=&quot;main-buysell__header__coin__dropdown&quot;]</value>
      <webElementGuid>9d40d3d5-fcf9-4d5b-b8fd-6f1c2e7cc694</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div/div/div/div/div/div/div/p[3]</value>
      <webElementGuid>99e209b1-254d-46e3-b898-2ebc698b3df6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[2]/following::p[3]</value>
      <webElementGuid>e473daac-c81e-408a-af26-d3c511c1cdff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download Tax Report'])[1]/following::p[3]</value>
      <webElementGuid>1b71e66f-c114-4d20-8a01-b6d27c138a7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BUY'])[1]/preceding::p[11]</value>
      <webElementGuid>3e3f79ff-3290-4f0b-95df-a88b90a3c461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SELL'])[1]/preceding::p[11]</value>
      <webElementGuid>6b11aebf-b2ae-4fcc-8472-aec269729763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select Coin']/parent::*</value>
      <webElementGuid>a37fa5cd-e7bb-4055-85c9-bf7297ee0ae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]</value>
      <webElementGuid>fc95abf5-2a2b-4008-941e-da0e2abca15f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Select Coin' or . = 'Select Coin')]</value>
      <webElementGuid>8763367d-9cdc-4c87-b573-b0dfbf562b1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
