<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Biconomy</name>
   <tag></tag>
   <elementGuidId>57d99b6e-692f-4bca-be5f-bf80c106f18a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='close']/div/div[3]/div[36]/div[2]/div[2]/p/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>515f1e9a-6c00-4b35-bfb1-711738b0f120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Biconomy</value>
      <webElementGuid>d72f6b0e-6e44-4caa-aef3-9e7fc7d356ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;close&quot;)/div[@class=&quot;vx-modal__container animate__animated animate__fadeIn md&quot;]/div[@class=&quot;modal-select-crypto__test&quot;]/div[@class=&quot;modal-select-crypto__item&quot;]/div[@class=&quot;flex gap-3 modal-select-crypto__item__fav&quot;]/div[@class=&quot;modal-select-crypto__item__details&quot;]/p[1]/span[1]</value>
      <webElementGuid>ea4c4ba9-42ba-4c06-acf5-7db13a67b9d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='close']/div/div[3]/div[36]/div[2]/div[2]/p/span</value>
      <webElementGuid>00d5bc85-4617-4011-bf81-60efc7fd738c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basic Attention Token'])[1]/following::span[1]</value>
      <webElementGuid>b9fecbd4-03bc-4b62-bbe1-0d711f3e28a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BarnBridge'])[1]/following::span[2]</value>
      <webElementGuid>c6e9a8ba-e85e-4628-9b29-941c21f9883f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BiFi'])[1]/preceding::span[1]</value>
      <webElementGuid>6ad2df48-5d1a-40e6-b688-3e20a7fd0d4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Binance USD'])[1]/preceding::span[2]</value>
      <webElementGuid>72334426-8a69-4b26-8d92-9aac3431675a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Biconomy']/parent::*</value>
      <webElementGuid>7b4d2a0b-9706-47be-85fe-573b546c5cba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[36]/div[2]/div[2]/p/span</value>
      <webElementGuid>625a593c-6179-4af0-ba7b-d4c50b8d97a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Biconomy' or . = 'Biconomy')]</value>
      <webElementGuid>d5e370f1-3a8e-411f-bd48-70de81f086e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
