<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Forgot password_p-checkbox-box</name>
   <tag></tag>
   <elementGuidId>938b84ff-66b7-4f2b-b486-a7e90f4390e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sign-in']/div/section/form/div[3]/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.p-checkbox-box</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a071373f-6374-4487-a020-63603911a2fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-checkbox-box</value>
      <webElementGuid>7d6f439c-aafa-4d7d-a0b6-ffafefa860fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d0422312-29cf-417b-9182-3ef7a1fc022a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9b7f70aa-6b42-46f3-ad00-7a034a7ac4d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sign-in&quot;)/div[@class=&quot;sign-in__container&quot;]/section[@class=&quot;sign-in&quot;]/form[@class=&quot;login-form&quot;]/div[@class=&quot;keep-me mb-2&quot;]/div[@class=&quot;checkbox-wrapper&quot;]/div[@class=&quot;p-checkbox p-component vx-checkbox primary vx-checkbox&quot;]/div[@class=&quot;p-checkbox-box&quot;]</value>
      <webElementGuid>c6fcdca7-2865-470b-b2c9-61a2ed89ef37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sign-in']/div/section/form/div[3]/div/div/div[2]</value>
      <webElementGuid>36bf5d8e-bd50-498f-aef3-501a7e6c48d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='▼'])[1]/following::div[6]</value>
      <webElementGuid>27e19124-8251-4245-896b-17c4803944e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keep me signed in on this computer'])[1]/preceding::div[1]</value>
      <webElementGuid>20df0a71-23bb-4133-b60b-9478dcf724ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/preceding::div[1]</value>
      <webElementGuid>1aae9457-2c42-4108-9750-aebb7faaaa4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]</value>
      <webElementGuid>9f9a809c-128a-48b9-87b8-e5f4d8c67a3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
