<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Exchange</name>
   <tag></tag>
   <elementGuidId>3d3c2501-ae26-41fb-acfa-a60c51ff5ecb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a5bac183-f49e-415e-b89a-4c1990364f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7856d56c-134e-4154-8188-891b4552ef6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vx-btn-md vx-btn-flat-white bd-2 with-icon</value>
      <webElementGuid>0ee5c41c-73f1-47f0-92e4-71277ca249cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Exchange </value>
      <webElementGuid>461355ad-7cc6-412d-826a-58975bb77234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;vx-app&quot;]/div[@class=&quot;app-content&quot;]/div[@class=&quot;history__container&quot;]/div[@class=&quot;history__wrapper&quot;]/div[@class=&quot;history__content&quot;]/div[@class=&quot;history__content__tab&quot;]/div[@class=&quot;history__content__tab__button&quot;]/div[@class=&quot;button-nav&quot;]/button[@class=&quot;vx-btn-md vx-btn-flat-white bd-2 with-icon&quot;]</value>
      <webElementGuid>faeddfd6-c68a-4ef7-917f-cb36b6a23863</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[9]</value>
      <webElementGuid>199b3cbc-2692-47ee-a3e7-5cdf88b703db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div/div[2]/div[2]/div[2]/div/button[3]</value>
      <webElementGuid>d3b176f7-a6f0-4337-aa68-e57dcc669a2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AMOUNT'])[1]/preceding::button[3]</value>
      <webElementGuid>61c8e665-ed6f-4299-89d9-dc00f3106986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>9848ed7f-cdcf-4c3b-a2a7-6819f3ade25e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Exchange ' or . = 'Exchange ')]</value>
      <webElementGuid>34b76261-0281-42d1-a97f-fb1cf2c9d972</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
