<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_DATE</name>
   <tag></tag>
   <elementGuidId>6bc7264b-c4e5-4a6b-9955-cc2ebce4b6f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.exchange__table__item__col__date__title > p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[3]/div/div/div[2]/div[3]/div[4]/div/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>6b8ff712-4574-4c2a-b3e9-2e0f5029f1aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DATE</value>
      <webElementGuid>e85ae628-8c7c-4c21-99d4-b4124e0746fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;vx-app&quot;]/div[@class=&quot;app-content&quot;]/div[@class=&quot;history__container&quot;]/div[@class=&quot;history__wrapper&quot;]/div[@class=&quot;history__content&quot;]/div[@class=&quot;exchange__wrapper&quot;]/div[@class=&quot;exchange__table&quot;]/div[@class=&quot;exchange__table__item&quot;]/div[@class=&quot;exchange__table__item__col&quot;]/div[@class=&quot;exchange__table__item__col__date__title&quot;]/p[1]</value>
      <webElementGuid>09f358fc-fccd-4251-8cff-55d2b89ae4a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div/div[2]/div[3]/div[4]/div/div/div/p</value>
      <webElementGuid>60b60dd8-d308-473f-b8ee-e92a08037901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Market'])[3]/preceding::p[140]</value>
      <webElementGuid>d9270277-1b5d-4eaf-9b24-bd0e2ddbc516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coins'])[3]/preceding::p[140]</value>
      <webElementGuid>e90291b7-a25a-42a4-8a8b-bbececbe726e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DATE']/parent::*</value>
      <webElementGuid>fabe1e56-1731-4f0c-8bad-7901b2ca183e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/p</value>
      <webElementGuid>c393335d-1842-47b5-af64-6582c2fc5550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'DATE' or . = 'DATE')]</value>
      <webElementGuid>1a3d8738-dd5c-435b-bf8b-8cc40cf3d856</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
