<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Success</name>
   <tag></tag>
   <elementGuidId>620b8a49-86b9-46e0-bd21-4bd7f508919c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[3]/div/div/div[2]/div[3]/div[4]/div[8]/div[9]/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>2304e959-5f9b-4526-b2e0-992c4b5398a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>success</value>
      <webElementGuid>0a1baee0-de62-421c-8104-4786359bbbc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Success</value>
      <webElementGuid>a666ca05-7fe5-405e-982c-f76a2e64fe74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;vx-app&quot;]/div[@class=&quot;app-content&quot;]/div[@class=&quot;history__container&quot;]/div[@class=&quot;history__wrapper&quot;]/div[@class=&quot;history__content&quot;]/div[@class=&quot;exchange__wrapper&quot;]/div[@class=&quot;exchange__table&quot;]/div[@class=&quot;exchange__table__item&quot;]/div[@class=&quot;exchange__table__item__col&quot;]/div[@class=&quot;exchange__table__item__col__status&quot;]/p[@class=&quot;success&quot;]</value>
      <webElementGuid>4ef07d43-45a1-448c-bf91-ad4b2ac9ba09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div/div[2]/div[3]/div[4]/div[8]/div[9]/div/p</value>
      <webElementGuid>6713b768-a6b6-4629-99f9-ae9dd5094eaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Market'])[3]/preceding::p[41]</value>
      <webElementGuid>0d774007-730d-4f7d-a7ae-8bda0942300f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coins'])[3]/preceding::p[41]</value>
      <webElementGuid>a5467d49-cbd8-411f-b4cd-5fa54b1b77bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[9]/div/p</value>
      <webElementGuid>410afc27-8193-495e-b1e9-6ac99d6c8187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Success' or . = 'Success')]</value>
      <webElementGuid>164ffa18-d286-441c-bbd2-937028313f9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
