<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Buy</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>2df48e85-b072-49c6-8afb-1ca79ef2f298</testSuiteGuid>
   <testCaseLink>
      <guid>b7b45e84-7166-497c-8c25-7a053d377edb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Auth/LoginDevelopment</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>6e500a16-1c37-45f5-a1d6-b1006fa558e9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Auth/Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>1f9f375c-b3f0-4ecd-8b74-675e8f4fe9df</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>ccbd8f89-b51d-44ba-9064-190dc50cba33</id>
         <masked>false</masked>
         <name>input_HNT</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/Trade/Buy/HNT</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d3c03eca-5ea9-427a-8893-b4b402d77375</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/HNT</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>d3c03eca-5ea9-427a-8893-b4b402d77375</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>input_HNT</value>
         <variableId>ccbd8f89-b51d-44ba-9064-190dc50cba33</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>619e6cb7-0446-4d48-9164-1cd52c4d66c7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Trade/Sell/HNT</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>8677f8b5-f6ce-45a4-af8f-bdff12f2916c</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/HNT</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>8677f8b5-f6ce-45a4-af8f-bdff12f2916c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>input_HNT</value>
         <variableId>475f32b2-4655-40ef-b2ba-b6fdb01de873</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>778d8ebf-629c-4836-a6bb-e9ed6b4ffa9b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Trade/Buy/XDC</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>df226969-f5d2-4c66-bd60-54fd67a1d1fc</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/XDC</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>df226969-f5d2-4c66-bd60-54fd67a1d1fc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>input_XDC</value>
         <variableId>acf0ea75-c1c2-4a53-b572-71875f8f7a30</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>be6d7ecc-db93-46d1-a8d8-24a7bf5c8274</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Trade/Sell/XDC</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>72cd977f-d9ed-43dd-a6b1-aa24121c6e54</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/XDC</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>72cd977f-d9ed-43dd-a6b1-aa24121c6e54</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>input_XDC</value>
         <variableId>5a818c83-2931-4d6c-a9f4-e5f5b74fb952</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d2d68c74-9616-407d-a915-1637a18b5971</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>34899d69-a83b-4952-a75e-acecb8485172</id>
         <masked>false</masked>
         <name>input_ARB</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/Trade/Buy/ARB</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b6c65883-6ced-49c1-9b38-27399cdd9b8d</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/ARB</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>b6c65883-6ced-49c1-9b38-27399cdd9b8d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>input_ARB</value>
         <variableId>34899d69-a83b-4952-a75e-acecb8485172</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5ab8b489-a759-4ae8-a949-badce253ed0c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>f3004c20-ec1f-4408-8703-102e658f4dd5</id>
         <masked>false</masked>
         <name>input_ARB</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/Trade/Sell/ARB</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>e1b507fb-aca5-4aec-84dd-3a986244d5b7</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/ARB</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>e1b507fb-aca5-4aec-84dd-3a986244d5b7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>input_ARB</value>
         <variableId>f3004c20-ec1f-4408-8703-102e658f4dd5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>55b600f6-28ff-4066-a5e3-20f52ccafd07</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Trade/Buy/DOGECOIN</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>85d5a4db-c4e9-4bc8-8037-c92a38fa2627</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DOGE</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>85d5a4db-c4e9-4bc8-8037-c92a38fa2627</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>input_DOGE</value>
         <variableId>a1d50d9b-c0e8-4501-b2f1-7d6563ce80ec</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>aac7e53b-3242-47cd-9ca1-5dad750c2b2e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Trade/Sell/DOGECOIN</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>2c493de8-f221-4418-8215-c85da8fbac97</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DOGE</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>2c493de8-f221-4418-8215-c85da8fbac97</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>input_DOGE</value>
         <variableId>e7b247b5-7aa8-4b2b-926d-c6e58b44993f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>93b34931-2b6a-4899-b92e-2a97e5326179</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Trade/Buy/SPACE ID</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>68c91544-eb7b-47ce-b73a-c3f93d9c7d02</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DOGE</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>68c91544-eb7b-47ce-b73a-c3f93d9c7d02</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>input_DOGE</value>
         <variableId>533f524e-ea6a-48b1-9aff-ec0740c032a3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0aafe3a6-93d3-4745-9e08-58bc4fee9ffd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Trade/Sell/SPACE ID</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>eb2cf5a5-68be-4c9b-ac73-ed7c2c57d90c</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DOGE</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>eb2cf5a5-68be-4c9b-ac73-ed7c2c57d90c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>input_DOGE</value>
         <variableId>3bab077c-1c38-4a58-8343-80a24d86b326</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
