<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Transaction History</name>
   <tag></tag>
   <elementGuidId>7fd8e5a1-95a4-462a-a927-e2762eeb3157</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.vx-btn-md.vx-btn-primary.bd-2.with-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>85efb8b2-ffbb-4b20-b7fb-27b8b88e9864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9983e1dc-8509-4bb9-8107-1c52bd3159d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vx-btn-md vx-btn-primary bd-2 with-icon</value>
      <webElementGuid>479b7ff7-5755-4eba-bf17-a9a70d3dd812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transaction History </value>
      <webElementGuid>8068ff9c-3458-40c1-bf64-c79bb7bce4ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;app-content&quot;]/div[@class=&quot;buysell&quot;]/div[@class=&quot;buysell__wrapper&quot;]/div[@class=&quot;buysell__status&quot;]/div[@class=&quot;status-buysell&quot;]/div[@class=&quot;status-buysell__wrapper&quot;]/div[@class=&quot;status-buysell__footer&quot;]/button[@class=&quot;vx-btn-md vx-btn-primary bd-2 with-icon&quot;]</value>
      <webElementGuid>2e6677b3-0694-4ed6-8720-a9bbf617ef16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[7]</value>
      <webElementGuid>f9b98f33-cb4d-4b41-ac40-bfc9ba0c9d62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div/div/div/div/div/div[3]/button</value>
      <webElementGuid>7dcc79ac-5f9f-4602-82a3-3a75fd84edf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[2]/following::button[1]</value>
      <webElementGuid>fd8af3d5-7d8c-4ae8-9b32-3480ac811a72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download Tax Report'])[1]/following::button[1]</value>
      <webElementGuid>3bd62dc3-3d80-4085-b55e-3dc7aa93bbb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Market'])[3]/preceding::button[2]</value>
      <webElementGuid>e67623ee-e923-4b39-ad8e-ecb81bc3139e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>117785fe-5a19-4faa-95d3-0fe04ba3ab84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Transaction History ' or . = 'Transaction History ')]</value>
      <webElementGuid>6976ef21-9b27-4dd7-8b9f-6468fb48277a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
