<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Create Account</name>
   <tag></tag>
   <elementGuidId>e6cd0aa1-023d-4ce4-98f0-0fd4483f2326</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.vx-btn-md.vx-btn-gradient.bd-2.with-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c1327595-0638-4467-915f-d095a733c07d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>5026e502-1fb2-465d-aa17-28bbacb9c1be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vx-btn-md vx-btn-gradient bd-2 with-icon</value>
      <webElementGuid>d80a7e7b-2b86-4e04-996f-54ed0f0f336f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>btn-submit</value>
      <webElementGuid>a88bce18-fab7-4226-9c55-ab1040dd441d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create Account </value>
      <webElementGuid>0a689205-a777-4195-9395-73e27334ca59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;vx-app&quot;]/div[@class=&quot;vx-register vx-register__container&quot;]/div[@class=&quot;vx-register__content&quot;]/div[@class=&quot;vx-register__wrapper&quot;]/div[@class=&quot;register-form__wrapper&quot;]/section[@class=&quot;register-form&quot;]/form[@class=&quot;register-form__form&quot;]/div[@class=&quot;mb-7&quot;]/button[@class=&quot;vx-btn-md vx-btn-gradient bd-2 with-icon&quot;]</value>
      <webElementGuid>0a8329bf-3eb4-401a-8fa9-aefc2c031456</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>ffc0b246-f937-4755-9fb4-8841259e4536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div[2]/div/section/form/div[6]/button</value>
      <webElementGuid>e6071b1a-c15c-4faa-80c4-3f378b769ccc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Referral Code (Optional)'])[1]/following::button[1]</value>
      <webElementGuid>f828330a-27d2-49f0-b313-718c8ce0425f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='special character'])[1]/following::button[1]</value>
      <webElementGuid>dfd63b3e-9354-4689-a17b-72402481af08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::button[1]</value>
      <webElementGuid>b46fe009-0cee-4fba-ad6c-9b3849c1f251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::button[1]</value>
      <webElementGuid>ae33314f-03a0-4094-9ef6-6b2732c4d26d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create Account']/parent::*</value>
      <webElementGuid>4ad22bbd-cf23-4be8-a33d-817495b6e93f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>ba8e9fc9-6d3b-4526-969f-a6a0de19684e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Create Account ' or . = 'Create Account ')]</value>
      <webElementGuid>e7313878-fd73-4f2e-89b6-bd045799056a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
