<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Aceh</name>
   <tag></tag>
   <elementGuidId>aea244ce-b7b1-441c-9773-0890790a912f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='pv_id_3_0']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.options-show > div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Aceh' or . = 'Aceh')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3fac4258-32a0-4abf-bebd-b5c22f274642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aceh</value>
      <webElementGuid>7b8fd882-4bdb-47a5-acf6-35545a3512aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_3_0&quot;)/div[@class=&quot;options-show&quot;]/div[1]</value>
      <webElementGuid>27a5b3a0-4f4c-4d1f-9b59-5655114be9d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='pv_id_3_0']/div/div</value>
      <webElementGuid>a282ba2d-e2a6-4668-9010-a019afa0cece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::div[11]</value>
      <webElementGuid>3140eb9e-7adc-453f-b348-779d165ebd10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[2]/following::div[11]</value>
      <webElementGuid>eb1e0929-b59e-4b17-92a4-7e5e34d24bbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bali'])[1]/preceding::div[1]</value>
      <webElementGuid>5f99ebc3-cba8-4e66-84ec-2462fbaae822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Banten'])[1]/preceding::div[3]</value>
      <webElementGuid>9784e62e-1511-4069-8381-f327bcf8939c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aceh']/parent::*</value>
      <webElementGuid>d93bcdd5-2a6f-40bc-9535-53b76a8fc275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div</value>
      <webElementGuid>1b1a09a5-743e-4fa7-9216-ff5679c766e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Aceh' or . = 'Aceh')]</value>
      <webElementGuid>684e3dae-d734-4d29-b20f-3f674d9ec2d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
