<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Choose Bank_p-dropdown-trigger</name>
   <tag></tag>
   <elementGuidId>800cdeb0-a877-49d5-8ae8-6fe7044c09aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.p-dropdown-trigger</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pv_id_1']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4fe9a7d5-0c9b-46ee-9e8b-9d95fb3a0420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-dropdown-trigger</value>
      <webElementGuid>c4e99f0f-aac2-48a3-ae3b-387095211d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_1&quot;)/div[@class=&quot;p-dropdown-trigger&quot;]</value>
      <webElementGuid>9934ca81-7e1e-419d-a5fc-b4503f6fb22a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pv_id_1']/div</value>
      <webElementGuid>c00db036-9f2f-4f51-8128-ac9aabf20416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose Bank'])[1]/following::div[1]</value>
      <webElementGuid>852fede5-f1a1-4c21-b9c2-1446e0a05b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qris'])[1]/following::div[3]</value>
      <webElementGuid>c788ec00-638d-4b93-bd83-3de66cca57ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Market'])[3]/preceding::div[7]</value>
      <webElementGuid>074d2fa9-fecf-4879-a277-b1bd282ba2f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div</value>
      <webElementGuid>2d6c92bd-b088-46f6-87dd-fbebf58c785f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
