<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bank Mandiri</name>
   <tag></tag>
   <elementGuidId>8199bd10-85ec-47ce-bcc9-fc8ef8c4571a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Bank Mandiri' or . = 'Bank Mandiri')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.bank-dropdown__item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='pv_id_1_0']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ab7534d1-55d9-4fcd-9eec-364ba44960f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bank-dropdown__item</value>
      <webElementGuid>402980c6-cb17-4cd3-928e-8548837ef8b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bank Mandiri</value>
      <webElementGuid>afc2222b-b3be-4d35-b878-fdff45057823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_1_0&quot;)/div[@class=&quot;bank-dropdown__item&quot;]</value>
      <webElementGuid>e6e20d8b-68c5-4076-b903-7bcae924e3d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='pv_id_1_0']/div</value>
      <webElementGuid>12b87039-bd22-4a65-a3b9-9884d7bc1eeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::div[12]</value>
      <webElementGuid>d632cf02-2150-466a-b362-706594ff35ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[2]/following::div[12]</value>
      <webElementGuid>05ed24da-bae0-4087-ae63-2050b6c62d26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank Permata'])[1]/preceding::div[2]</value>
      <webElementGuid>6a2ee282-e975-4084-8500-a3153ce4778c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/ul/li/div</value>
      <webElementGuid>17323597-2e33-40a4-9b1e-caf45fcdca07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Bank Mandiri' or . = 'Bank Mandiri')]</value>
      <webElementGuid>428a63ac-f61d-4144-9e17-e75487d90201</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
