<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Deposit</name>
   <tag></tag>
   <elementGuidId>ea480e7c-bfe8-4b8d-88b3-cb35c394504f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.content-step__title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[3]/div/div/p</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;app&quot;)/div[@class=&quot;vx-app&quot;]/div[@class=&quot;app-content&quot;]/div[@class=&quot;deposit&quot;]/div[@class=&quot;content-step&quot;]/p[@class=&quot;content-step__title&quot;][count(. | //p[@class = 'content-step__title' and (text() = 'Deposit' or . = 'Deposit')]) = count(//p[@class = 'content-step__title' and (text() = 'Deposit' or . = 'Deposit')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>b4584d51-1dd4-488c-af70-6eecfea1a4f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>content-step__title</value>
      <webElementGuid>7ef10938-10fb-4283-ac4c-d0eeaf569c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Deposit</value>
      <webElementGuid>fd10c968-0fc1-4067-a270-69ccf0fa4731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;vx-app&quot;]/div[@class=&quot;app-content&quot;]/div[@class=&quot;deposit&quot;]/div[@class=&quot;content-step&quot;]/p[@class=&quot;content-step__title&quot;]</value>
      <webElementGuid>7be4e1c9-fca0-449a-a8d6-6ea7f6f6cfb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div/p</value>
      <webElementGuid>31fd5dd3-8658-4c09-80b5-f0fe7891d2ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[2]/following::p[1]</value>
      <webElementGuid>9b327726-2f51-4ce0-bf26-9f7c2a0a2558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download Tax Report'])[1]/following::p[1]</value>
      <webElementGuid>424a5b9a-8350-402a-9cec-dd00f634308e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login with your USER ID and PASSWORD'])[1]/preceding::p[8]</value>
      <webElementGuid>7d13818b-d327-4945-87a4-c932e7308d96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/p</value>
      <webElementGuid>0ac27d18-77fc-408b-8638-e9739c2ac718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Deposit' or . = 'Deposit')]</value>
      <webElementGuid>c9bdb3f4-2bcb-419c-bf13-e1787e4a84a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
